### ISSUE TITLE
Choose a virtual environment solution

### ISSUE THREAD

**Issue by hajicj** [kukas/melody_extraction#6]
Based on #5, choose an appropriate virtualization solution for switching between algorithms.

I would strongly suggest looking into the [Anaconda](https://www.continuum.io/) distribution and the [conda](https://conda.io/docs/intro.html) environment manager.

The next level of virtualization would be [Docker](https://www.docker.com/).

**Comment by kukas** [comment]
I have chosen [virtualenv](https://virtualenv.pypa.io/en/stable/) as a virtualization solution. Mainly because Anaconda seems unnecessarily complex for our purposes. I tested virtualenv by running the algorithms in parallel (see 7c28474c33f2e96388a2788fd25752c552e1fd7a) it seems to work and in theory any subprocess sould keep its own env. variables isolated.

I also prepared an install script to set up new virtual environments. (This is needed since virtualenv uses absolute paths in generated scripts so it is not easy to transfer them) See ee61439b58686d74c6f12d8c9d187c56c4b59ab3
